# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-20 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180607_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='priority',
            field=models.CharField(default='low', max_length=10),
        ),
    ]
