# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-19 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180607_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='alert_mode',
            field=models.CharField(default='Email', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
