# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-21 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_member_priority'),
        ('accounts', '0009_auto_20180619_1244'),
    ]

    operations = [
    ]
