# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-12 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20180611_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='allowed_nagging',
        ),
        migrations.AlterField(
            model_name='check',
            name='status',
            field=models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('new', 'New'), ('paused', 'Paused'), ('nagging', 'Nagging')], default='new', max_length=6),
        ),
    ]
