# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-12 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20180612_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='nagging_interval',
        ),
        migrations.RemoveField(
            model_name='check',
            name='next_nagging',
        ),
        migrations.AlterField(
            model_name='check',
            name='status',
            field=models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('new', 'New'), ('paused', 'Paused')], default='new', max_length=6),
        ),
    ]
