# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-12 19:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20180612_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='nagging_interval',
            field=models.DurationField(default=datetime.timedelta(0, 3600)),
        ),
        migrations.AddField(
            model_name='check',
            name='next_nagging',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='status',
            field=models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('new', 'New'), ('paused', 'Paused'), ('nag', 'Nag')], default='new', max_length=6),
        ),
    ]
