# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-14 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20180612_1422'),
        ('api', '0031_auto_20180612_1940'),
    ]

    operations = [
    ]
