# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-19 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20180614_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='nag_status',
            field=models.BooleanField(default=False),
        ),
    ]
