# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-20 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20180619_0208'),
        ('api', '0034_check_nag_status'),
    ]

    operations = [
    ]
