# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-21 07:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20180620_1646'),
        ('api', '0035_merge_20180620_1607'),
    ]

    operations = [
    ]
