# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-21 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_merge_20180621_0742'),
        ('api', '0035_merge_20180620_1723'),
    ]

    operations = [
    ]
