# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-19 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0002_faq_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='media',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
